on:
  push:
    branches:
    - main
    - feature/*
    - release/*
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  checks: write
  issues: read
  pull-requests: write

name: Deploy ALZ Identity

jobs:
  run_checks:
    uses: alztestappvia/alz_cicd_templates/.github/workflows/terraform-checks.yaml@main
    name: Run Checks
    secrets:
      GH_TOKEN: ${{ secrets.ALZ_GITHUB_MODULE_READ_TOKEN }}

  deploy_to_test:
    uses: ./.github/workflows/template_deploy-to-environment.yml
    name: Deploy to Test
    needs: run_checks
    with:
      environment: 'test'
    secrets:
      GH_TOKEN: ${{ secrets.ALZ_GITHUB_MODULE_READ_TOKEN }}

  deploy_to_prod:
    uses: ./.github/workflows/template_deploy-to-environment.yml
    name: Deploy to Prod
    needs: run_checks
    with:
      environment: 'prod'
    secrets:
      GH_TOKEN: ${{ secrets.ALZ_GITHUB_MODULE_READ_TOKEN }}